import type { Metadata } from "next";
import LayoutWrapper from "@/components/LayoutWrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <meta
        name="viewport"
        content="bg-gradient-background dark:bg-background"
      ></meta>
      <body className="bg-[var(--background)]">
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
